### PR TITLE
Add section about test naming

### LINKED ISSUE #131: Add standard for naming tests
I have seen some conflicting ways of naming Clojure tests:

- `(deftest xyzzy-test ...)`
- `(deftest xyzzy-tests ...)`
- `(deftest xyzzy ...)`
- `(deftest test-xyzzy ...)`

Clojure test namespaces seem to be fairly consistent: `project.xyzzy-test`. I think the first form is most idiomatic, but I came to the Clojure style guide for advice, and it didn't appear to have an opinion on this yet.

### PR DESCRIPTION
**Pull request by lvh**
Closes #131.

### CODE REVIEW

**Comment by lvh** [comment]
I also made the thing right before the testing section look more like the rest of the README.

**Comment by bbatsov** [comment]
Thanks! Now we should continue with more advices like - use `testing` to introduce some context for assertions and so on...

**Comment by lvh** [comment]
Yep. Would you like me to file separate issues for that? I know you mentioned in #131 you'd like to see more general stuff, it seems like that should be at least one more issue, so I'll go file that :)

**Comment by bbatsov** [comment]
Sounds good.

**Pull request merged**
