### PR TITLE
Recommend using a single empty line between top-level forms

### LINKED ISSUE #170: How many empty lines between top-level forms?
The rule for [top-level-forms](https://github.com/bbatsov/clojure-style-guide#empty-lines-between-top-level-forms) says:

> Use empty lines between top-level forms. An exception to the rule is the grouping of related defs together.

It doesn't say how many empty lines should be put between top level forms though. Most open source Clojure code including Clojure itself, as well as the code samples in the style guide use a single empty line between forms. Some people do use two lines though. Is this something the style guide wants to take a position on?

### PR DESCRIPTION
**Pull request by danielcompton**
Fixes #170

### CODE REVIEW

**Comment by eigenhombre** [comment]
I was originally 👍 on this but have always preferred two-line spacing between toplevel forms and see on https://crossclj.info/ that several popular projects use two-line spacing.  So I'm not sure we should advocate for one or the other in the style guide.

**Comment by danielcompton** [comment]
Which projects do you see using two-line spacing?

**Comment by eigenhombre** [comment]
https://crossclj.info/ns/nightlight/lein-nightlight/2.2.5/leiningen.nightlight.html
https://crossclj.info/ns/arichiardi/humane-test-output/0.9.1/pjstadig.util.html
jumped out at me from the (presumably randomly selected) "Most recently updated projects" list; however, looking through several more examples I can see that you are right, the great majority are single-line spaced.  So, I withdraw my objection ;-).

**Comment by danielcompton** [comment]
One other thought that has just come up is that if you have `s/fdef`'s above or below a function, they would look a bit funny being two lines away from the function.

```clj
(defn foo [xyz]
  (bar xyz))


(s/fdef foo
        :args (s/cat :foo ::foo))

;; vs.

(defn foo [xyz]
  (bar xyz))

(s/fdef foo
        :args (s/cat :foo ::foo))
```

**Comment by bbatsov** [comment]
@danielcompton I think you should also add some bad example for two consecutive blank lines.

**Comment by danielcompton** [comment]
Thanks, I've added that.

**Comment by bbatsov** [comment]
Thanks!

**Pull request merged**
